name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install imagemagick
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Build
        run: npx nativefier --name "Jira" --icon "./icon-mac.png" ${{ secrets.JIRA_URL }}

      - uses: actions/upload-artifact@master
        with:
          name: Mac App
          path: Jira-darwin-x64/Jira.app
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Build
        run: npx nativefier --name "Jira" --icon "./icon-windows.icon" ${{ secrets.JIRA_URL }}

      #- uses: actions/upload-artifact@master
      #  with:
      #    name: Windows App
      #    path: Jira-darwin-x64/Jira.app
      

      - name: Stuff
        run: ls -al
        shell: bash
      
      #- uses: actions/upload-artifact@master
      #  with:
      #    name: Windows App
      #    path: .
